- hosts: all
  serial: 1
  gather_facts: no
  tasks:
    - name: Stop Kasm Services
      shell: /opt/kasm/bin/stop
      register: stop_output
      changed_when: '"done" in stop_output.stderr'
      become: true